### ISSUE TITLE
Goal, what should make, etc?

### ISSUE THREAD

**Issue by rafaeelneto** [cogitovsmachina/7minworkout#1]
would of know the goal of project, how you want as work?

**Comment by vic** [comment]
Guys have you looked at this ? http://lifehacker.com/scientific-7-minute-workout-makes-your-android-phone-an-706714821

**Comment by rafaeelneto** [comment]
Ok, i am understanding. you want all free and with synchrony with the cloud?

**Comment by rafaeelneto** [comment]
sorry my english, please ;)
